//
//  TableViewControllerPresenter.swift
//  ToDoList
//
//  Created by Сергей Вихляев on 03.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TableViewControllerPresentationLogic: class {
}

protocol TableViewControllerViewControllerOutput {
    func viewIsReady()
    func saveTask(withTitle title: String)
}

class TableViewControllerPresenter: NSObject, TableViewControllerPresentationLogic {
    var interactor: TableViewControllerBusinessLogic!
    weak var viewController: TableViewControllerDisplayLogic!
    weak var tableView: UITableView?
    var router: TableViewControllerRoutingLogic!
    
    // MARK: Presentation Logic
    
    func tableViewChangesDone() {
        //viewController.tableViewChangesDone()
    }
}

extension TableViewControllerPresenter: TableViewControllerViewControllerOutput {
    func viewIsReady() {
        
        tableView?.beginUpdates()
        
        guard let count = interactor?.prepareDataAndReturnCountOfInsertRows() else { return}
        
        var indexPaths: [IndexPath] = []
        for row in 0 ..< count {
            indexPaths.append(IndexPath(row: row, section: 0))
        }
        
        tableView?.insertRows(at: indexPaths, with: .automatic)
        
        tableView?.endUpdates()
    }
    
    func saveTask(withTitle title: String) {
        tableView?.beginUpdates()
        interactor?.tableViewChangeBlockAddTask(withTitle: title)()
        tableView?.insertRows(at: [IndexPath(row: 0, section: 0)], with: .automatic)
        tableView?.endUpdates()
    }
}

extension TableViewControllerPresenter: UITableViewDelegate {}
