//
//  TableViewControllerViewController.swift
//  ToDoList
//
//  Created by Сергей Вихляев on 03.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TableViewControllerDisplayLogic: class {
    // func tableViewChangesDone()
}

class TableViewController: UITableViewController {
    var presenter: TableViewControllerViewControllerOutput!
    
    private var addBarButtonItem: UIBarButtonItem!
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    // MARK: Action
    func tableViewChangesDone() {
        tableView?.beginUpdates()
        tableView?.endUpdates()
    }
}

// MARK: Setup
extension TableViewController {
    private func setup() {
        //
        self.title = "To-Do List"
        //
        
        registerXibs()
        setupBarButtons()
    }
    
    private func registerXibs() {
        tableView.register(TaskTableViewCell.self, forCellReuseIdentifier: TaskTableViewCell.reuseIdentifier())
    }
    
    private func setupBarButtons() {
        addBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(showAddNewTaskAlertController))
        addBarButtonItem.style = .done
        navigationItem.rightBarButtonItem = addBarButtonItem
    }
    
    @objc private func showAddNewTaskAlertController() {
        
        let alertController = UIAlertController(title: "New Task", message: "Please add new task", preferredStyle: .alert)
        
        let save = UIAlertAction(title: "Save", style: .default) { [weak self] (action) in
            let tf = alertController.textFields?.first
            if let text = tf?.text {
                self?.presenter.addTask(text)
            }
        }
        
        let cancel = UIAlertAction(title: "Cancel", style: .cancel, handler: nil)
        
        alertController.addTextField(configurationHandler: nil)
        alertController.addAction(save)
        alertController.addAction(cancel)
        
        present(alertController, animated: true, completion: nil)
    }
}

extension TableViewController: TableViewControllerDisplayLogic {}
