//
//  TableViewControllerConfigurator.swift
//  ToDoList
//
//  Created by Сергей Вихляев on 03.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class TableViewControllerConfigurator: BaseConfiguratorProtocol {
    func configure(viewController: UIViewController, navigationController: UINavigationController?) {
        let viewController = viewController as! TableViewController
        
        let presenter = TableViewControllerPresenter()
        let interactor = TableViewControllerInteractor()
        let router = TableViewControllerRouter(withNavigationController: navigationController)

        interactor.presenter = presenter
        viewController.presenter = presenter
        presenter.viewController = viewController
        presenter.interactor = interactor
        presenter.router = router
                
        viewController.tableView.delegate = presenter
        viewController.tableView.dataSource = interactor
        
        presenter.tableView = viewController.tableView
    }
    
    // MARK: - Creating of RootViewController()
    class func rootViewController() -> UIViewController {
        let navigationController = UINavigationController()
        
        let viewController = TableViewController()
        
        TableViewControllerConfigurator().configure(viewController: viewController, navigationController: navigationController)
        
        navigationController.viewControllers = [viewController]
        
        return navigationController
    }
}
