//
//  TableViewControllerRouter.swift
//  ToDoList
//
//  Created by Сергей Вихляев on 03.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TableViewControllerRoutingLogic {
    func routeTo(target: TableViewControllerRouter.Targets)
}

class TableViewControllerRouter: TableViewControllerRoutingLogic {

    private var navigationController: UINavigationController?
    init(withNavigationController: UINavigationController?) {
        self.navigationController = withNavigationController
    }

    enum Targets {
        case t1
        // ...
    }

    func routeTo(target: TableViewControllerRouter.Targets) {
        switch target {
        case .t1:
            print(#function)
            /*let someVC = SomeVC(nibName: someVC.kStoryboardID, bundle: nil)
             SomeConfigurator().configure(viewController: someVC, navigationController: self.navigationController)
            navigationController?.pushViewController(someVC, animated: true)*/
        }
    }
}
