//
//  TableViewControllerPresenter.swift
//  ToDoList
//
//  Created by Сергей Вихляев on 03.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TableViewControllerPresentationLogic: class {
}

protocol TableViewControllerViewControllerOutput {
    func addTask(_ task: String)
}

class TableViewControllerPresenter: NSObject, TableViewControllerPresentationLogic {
    var interactor: TableViewControllerBusinessLogic!
    weak var viewController: TableViewControllerDisplayLogic!
    weak var tableView: UITableView?
    var router: TableViewControllerRoutingLogic!
    
    // MARK: Presentation Logic
    
    func tableViewChangesDone() {
        viewController.tableViewChangesDone()
    }
}

extension TableViewControllerPresenter: TableViewControllerViewControllerOutput {
    func addTask(_ task: String) {
        tableView?.beginUpdates()
        interactor?.tableViewChangeBlockAddTask(task)()
        tableView?.insertRows(at: [IndexPath(row: 0, section: 0)], with: .automatic)
        tableView?.endUpdates()
    }
}

extension TableViewControllerPresenter: UITableViewDelegate {}
